#!/bin/bash
set -ex


#################  GENERAL FLAVOR RELATED CHANGES ############ 
BWFLA='/home/bwfla'

echo "deb http://packages.bw-fla.uni-freiburg.de/ trusty bwfla" > /etc/apt/sources.list.d/bwfla.list
echo -e "Package: *\nPin: release c=bwfla\nPin-Priority: 1001" > /etc/apt/preferences.d/pin-bwfla.pref
apt-get update -y
mkdir -p $BWFLA/.bwFLA


################# 'COMMON' RELATED CHANGES ################## 
cat << EOF > $BWFLA/.bwFLA/CommonConf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<commonConf>
</commonConf>
EOF


############# 'IMAGEARCHIVE' RELATED CHANGES ############## 
cat << EOF > $BWFLA/.bwFLA/ImageArchiveConf.xml
<?xml version="1.0" encoding="UTF-8"?>

<imageArchiveConf>
  <archiveBase>/home/bwfla/image-archive</archiveBase>
  <httpPrefix>http://%PUBLIC_IP%/image-archive/</httpPrefix>
</imageArchiveConf>
EOF

#echo -e '[generic]\n\texportpath = /home/bwfla/image-archive/nbd-export' > '/home/bwfla/nbd.conf' 
#apt-get install -y --force-yes nbd-server 
apt-get install -y --force-yes debconf-utils

################# 'EAAS' RELATED CHANGES ################## 
cat << EOF > $BWFLA/.bwFLA/EaasConf.xml
<?xml version="1.0" encoding="UTF-8"?>

<eaasConf>
    <bladeClusterPlugin>
        <bladeConnection>
            %NODES%
        </bladeConnection>
    </bladeClusterPlugin>   
</eaasConf>
EOF

echo "eaas-common eaas-common/configure false" | debconf-set-selections
echo "eaas-common eaas-common/public_ip_port 1.2.3.4:8080" | debconf-set-selections

################# 'EMUCOMP' RELATED CHANGES ################## 
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes \
hatari \
hsj \
basilisk2 \
dosbox \
guacd \
libguac-client-sdlonp0 \
libsdl1.2debian \
qemu-utils \
qemu-system-x86 \
qemu-system-ppc \
sheepshaver \
libcurl3 \
libcurl3-gnutls \
qemu-block-extra \
xmount \
libxmount-input-qemu \
debconf-utils \
emil \
eaas-fits

cat << EOF > $BWFLA/.bwFLA/EmucompConf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<emucompConf>
    <controlUrlAddressHttp>%PUBLIC_IP%</controlUrlAddressHttp>
    <qemuBean>/usr/bin/qemu-system-</qemuBean>
    <basiliskBean>/usr/bin/BasiliskII.real</basiliskBean>
    <sheepShaverBean>/usr/bin/SheepShaver</sheepShaverBean>
    <dosBoxBean>/usr/bin/dosbox</dosBoxBean>
    <vboxBean>
        <vboxHeadlessExec>/usr/bin/VBoxSDL</vboxHeadlessExec>
        <vboxManageExec>/usr/bin/VBoxManage</vboxManageExec>
    </vboxBean>
    <hatariBean>/usr/bin/hatari</hatariBean>
    <vdeSwitchBean>/usr/bin/vde_switch</vdeSwitchBean>
    <viceBean>
        <c64>/usr/bin/x64</c64>
        <c128>/usr/bin/x128</c128>
    </viceBean>
    <pceBean>
        <atarist>/usr/bin/pce-atarist</atarist>
        <ibmpc>/usr/bin/pce-ibmpc</ibmpc>
        <macplus>/usr/bin/pce-macplus</macplus>
    </pceBean>
    <kegsBean>/usr/bin/kegs</kegsBean>
</emucompConf>
EOF


################# 'FITS' RELATED CHANGES ################## 
cat << EOF > $BWFLA/.bwFLA/FitsConf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<fitsConf>
    <fitsHome>$BWFLA/misc/fits</fitsHome>
</fitsConf>
EOF

################# 'OBEJCTS' RELATED CHANGES #################
cat << EOF > $BWFLA/.bwFLA/ObjectArchiveConf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<objectArchiveConf>
    <objDir>$BWFLA/object-archives/</objDir>
    <httpExport>http://%PUBLIC_IP%/object-archive/</httpExport>
</objectArchiveConf>
EOF


mkdir -p /home/bwfla/classification-cache/

cat << EOF > $BWFLA/.bwFLA/EmilConf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<emilConf>
    <objectArchive>%PUBLIC_IP%</objectArchive>
    <imageArchive>%PUBLIC_IP%</imageArchive>
    <softwareArchive>%PUBLIC_IP%</softwareArchive>
    <embedGw>http://%PUBLIC_IP%/faces/pages/workflow-embedinit/WF_EMN_0.xhtml</embedGw>
    <eaasGw>http://%PUBLIC_IP%/eaas-ejb/EaasWS?wsdl</eaasGw>
    <cachedClassificationPath>/home/bwfla/classification-cache/</cachedClassificationPath>
    <emilEnvironmentsPath>/home/bwfla/emil-environments</emilEnvironmentsPath>
</emilConf>
EOF

################# 'WORKFLOWS' RELATED CHANGES #################
mkdir -p $BWFLA/{software-archive,object-archives,object-metadata,system-envs,pics}
cat << EOF > $BWFLA/.bwFLA/WorkflowsConf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<workflowsConf>
    <imageArchive>%IMAGE_ARCHIVE%</imageArchive>
    <eaasGw>http://%EAAS_GATEWAY%/eaas-ejb/EaasWS?wsdl</eaasGw>
    <objectArchive>%OBJECT_ARCHIVE%</objectArchive>
    <metaDir>$BWFLA/object-metadata</metaDir>
    <picDir>$BWFLA/pics</picDir>
    <swArchive>$BWFLA/software-archive/swarchive.xml</swArchive>
    <embedGw>http://%PUBLIC_IP%/faces/pages/workflow-embed/WF_EM_0.xhtml</embedGw>
</workflowsConf>
EOF

mkdir -p $BWFLA/software-archive/{storage,incoming}
echo "{\"type\":\"FILE\",\"name\":\"User-Objects\",\"localPath\":\"$BWFLA/user-objects/\"}" > $BWFLA/object-archives/user-objects.json
cat << EOF > $BWFLA/software-archive/swarchive.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<fileSoftwareArchive>
  <name>User-Software</name>
  <description>A user provided/maintained software archive</description>
  <archiveDirectory>$BWFLA/software-archive/storage</archiveDirectory>
  <incomingDirectory>$BWFLA/software-archive/incoming</incomingDirectory>
  <exportUrlBase>http://%PUBLIC_IP%/swarchive/</exportUrlBase>
</fileSoftwareArchive>
EOF

apt-get install -y --force-yes pmount hfsutils mkisofs fuseiso  
echo -en \\r/dev/loop{0..7}\\n > /etc/pmount.allow
chmod g+x /usr/bin/pmount 
chmod g+x /usr/bin/pumount
ln -sf /sbin/losetup /usr/bin/
ln -sf /sbin/sfdisk /usr/bin/
ln -sf /sbin/mkfs.* /usr/bin/
ln -sf /sbin/mkdosfs /usr/bin/

rm -rf /usr/lib/xmount/libxmount_input_aff.so

# add the bwfla user to the fuse group
adduser bwfla fuse
# allow_other required for xmount
sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf
